--- Head ---

DROP DATABASE IF EXISTS azienda;
CREATE DATABASE azienda;

SET search_path TO azienda;
DROP SCHEMA IF EXISTS noleggi CASCADE;
CREATE SCHEMA noleggi;

SET search_path TO noleggi;



--- Body ---

-- Creazione tipi ENUM per tabelle noleggio e sconto
CREATE TYPE stato_restituzione_enum AS ENUM ('Buono', 'Danneggiato');
CREATE TYPE descrizione_sconto_enum AS ENUM ('5 noleggi', '10 noleggi', '25 noleggi', '50 noleggi');
CREATE TYPE stato_noleggio_enum AS ENUM ('Attivo', 'Chiuso', 'Prenotato');

CREATE TABLE store (
    store_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    localita VARCHAR(255) NOT NULL
);
 
CREATE TABLE fornitore (
    fornitore_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    email VARCHAR(50) NOT NULL
);
 
CREATE TABLE staff (
    staff_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    
    ruolo VARCHAR(15) NOT NULL, -- 'responsabile' o 'dipendente'
    nome VARCHAR(50) NOT NULL,
    cognome VARCHAR(50) NOT NULL,
    matricola INT UNIQUE NOT NULL
);
 
CREATE TABLE cliente (
    cliente_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    cognome VARCHAR(50) NOT NULL,
    data_nascita DATE NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    cellulare VARCHAR(20) NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL,
    indirizzo VARCHAR(50) NOT NULL,
    id_liberatoria VARCHAR(50) NOT NULL,
    data_firma_liberatoria DATE NOT NULL
);
 
CREATE TABLE video (
    video_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titolo VARCHAR(50) NOT NULL,
    nome_regista VARCHAR(50) NOT NULL,
    cognome_regista VARCHAR(50) NOT NULL,
    casa_produttrice VARCHAR(50) NOT NULL,
    durata_min INT NOT NULL,
    genere VARCHAR(15) NOT NULL
);
 
CREATE TABLE attore (
    attore_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    cognome VARCHAR(50) NOT NULL
);

-- Per relazione molti a molti, in tabella intermedia aggiungo direttamente le FKs, perché la creo dopo aver creato le altre due tabelle "madri"
CREATE TABLE video_attore (
    video_id INT NOT NULL REFERENCES video(video_id),
    attore_id INT NOT NULL REFERENCES attore(attore_id),
    PRIMARY KEY (video_id, attore_id)
);
 
-- Copia fisica singola di un video, presente in un negozio, arrivata da un fornitore
CREATE TABLE copia_video (
    copia_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    
    data_carico_fornitore DATE NOT NULL,
	data_ritiro_fornitore DATE
);
 
CREATE TABLE tariffa (
    tariffa_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prezzo_giorno DECIMAL(5,2) NOT NULL,
    gg_min SMALLINT NOT NULL,
    gg_max SMALLINT NOT NULL
);
 
CREATE TABLE sconto (
    sconto_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descrizione descrizione_sconto_enum NOT NULL,
    percentuale_sconto DECIMAL(5,2) NOT NULL
);

CREATE TABLE noleggio (
    noleggio_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    data_restituzione DATE, -- NULL finché non rientra
    stato_restituzione stato_restituzione_enum, -- 'buono' / 'danneggiato', nullable perché rivalutato ogni volta al rientro
    stato_noleggio stato_noleggio_enum, -- 'attivo', 'chiuso', 'prenotato'
	importo_pagato DECIMAL(6,2) NOT NULL
);

CREATE TABLE incentivo (
    incentivo_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    periodo DATE NOT NULL,
    soglia_raggiunta INT NOT NULL,
    importo DECIMAL(5,2) NOT NULL
);



--- Foreign Keys ---

-- Le aggiungo prima di popolare le tabelle altrimenti non le posso mettere come NOT NULL
-- FK per tabella di staff
ALTER TABLE staff ADD COLUMN store_id INT NOT NULL REFERENCES store(store_id);

-- FK per tabella copia_video
ALTER TABLE copia_video ADD COLUMN video_id INT NOT NULL REFERENCES video(video_id);
ALTER TABLE copia_video ADD COLUMN fornitore_id INT NOT NULL REFERENCES fornitore(fornitore_id);
ALTER TABLE copia_video ADD COLUMN store_id INT NOT NULL REFERENCES store(store_id);

-- FK per tabella noleggio
ALTER TABLE noleggio ADD COLUMN copia_id INT NOT NULL REFERENCES copia_video(copia_id);
ALTER TABLE noleggio ADD COLUMN cliente_id INT NOT NULL REFERENCES cliente(cliente_id);
ALTER TABLE noleggio ADD COLUMN staff_id INT NOT NULL REFERENCES staff(staff_id);
ALTER TABLE noleggio ADD COLUMN tariffa_id INT NOT NULL REFERENCES tariffa(tariffa_id);
ALTER TABLE noleggio ADD COLUMN sconto_id INT REFERENCES sconto(sconto_id); -- nullable se nessuno sconto applicabile

-- FK per tabella incentivo
ALTER TABLE incentivo ADD COLUMN staff_id INT NOT NULL REFERENCES staff(staff_id);



--- Population ---
-- Seguo ordine delle tabelle, con tabelle madri prima e poi quelle che le referenziano dopo

-- STORE (8 punti vendita)
INSERT INTO store (localita) VALUES
('Milano'),
('Monza'),
('Bergamo'),
('Brescia'),
('Como'),
('Varese'),
('Lecco'),
('Pavia');
 
-- FORNITORE (6 fornitori)
INSERT INTO fornitore (nome, telefono, email) VALUES
('VideoDistribuzione SRL', '0212345678', 'info@videodistribuzione.it'),
('FilmSupply SPA', '0298765432', 'contatti@filmsupply.it'),
('CineNoleggio Group', '0311122233', 'sales@cinenoleggio.it'),
('MovieBox Distribution', '0355566677', 'info@moviebox.it'),
('ScreenWorks SRL', '0399988877', 'ordini@screenworks.it'),
('ReelSupply SPA', '0244455566', 'info@reelsupply.it');
 
-- STAFF (1 responsabile + addetti per negozio) - richiede store_id già esistenti
INSERT INTO staff (store_id, ruolo, nome, cognome, matricola) VALUES
(1, 'responsabile', 'Marco', 'Rossi', 1001),
(1, 'dipendente', 'Giulia', 'Bianchi', 1002),
(1, 'dipendente', 'Luca', 'Verdi', 1003),
(2, 'responsabile', 'Sara', 'Neri', 1004),
(2, 'dipendente', 'Paolo', 'Colombo', 1005),
(3, 'responsabile', 'Elena', 'Ferrari', 1006),
(3, 'dipendente', 'Davide', 'Russo', 1007),
(4, 'responsabile', 'Chiara', 'Esposito', 1008),
(4, 'dipendente', 'Marco', 'Longhi', 1013),
(5, 'responsabile', 'Andrea', 'Romano', 1009),
(5, 'dipendente', 'Beatrice', 'Fumagalli', 1014),
(6, 'responsabile', 'Francesca', 'Gallo', 1010),
(6, 'dipendente', 'Michele', 'Riva', 1015),
(7, 'responsabile', 'Simone', 'Conti', 1011),
(7, 'dipendente', 'Elisa', 'Pirola', 1016),
(8, 'responsabile', 'Valentina', 'Ricci', 1012),
(8, 'dipendente', 'Tommaso', 'Villa', 1017);
 
-- CLIENTE
INSERT INTO cliente (nome, cognome, data_nascita, telefono, cellulare, email, indirizzo, id_liberatoria, data_firma_liberatoria) VALUES
('Alessandro', 'Moretti', '1990-05-14', '021112233', '3331112233', 'a.moretti@mail.it', 'Via Roma 12, Milano', 'LIB-0001', '2023-01-10'),
('Federica', 'Bruno', '1985-11-02', '021113344', '3332223344', 'f.bruno@mail.it', 'Via Torino 5, Milano', 'LIB-0002', '2023-01-15'),
('Matteo', 'Villa', '1995-03-21', '039221100', '3333334455', 'm.villa@mail.it', 'Via Manzoni 8, Monza', 'LIB-0003', '2023-02-01'),
('Sofia', 'Barbieri', '1992-07-30', '035556677', '3334445566', 's.barbieri@mail.it', 'Via Verdi 3, Bergamo', 'LIB-0004', '2023-02-10'),
('Riccardo', 'Fontana', '1988-09-17', '030445566', '3335556677', 'r.fontana@mail.it', 'Via Dante 20, Brescia', 'LIB-0005', '2023-03-05'),
('Martina', 'Galli', '1998-01-25', '031667788', '3336667788', 'm.galli@mail.it', 'Via Cavour 15, Como', 'LIB-0006', '2023-03-20'),
('Davide', 'Ferraro', '1983-04-12', '033299887', '3337778899', 'd.ferraro@mail.it', 'Via Garibaldi 22, Varese', 'LIB-0007', '2023-04-02'),
('Chiara', 'Marino', '1996-12-08', '034155667', '3338889900', 'c.marino@mail.it', 'Via Mazzini 9, Lecco', 'LIB-0008', '2023-04-18'),
('Lorenzo', 'De Angelis', '1991-06-27', '038211223', '3339990011', 'l.deangelis@mail.it', 'Via Battisti 14, Pavia', 'LIB-0009', '2023-05-05'),
('Giorgia', 'Palumbo', '1994-10-03', '021998877', '3330001122', 'g.palumbo@mail.it', 'Via XX Settembre 30, Milano', 'LIB-0010', '2023-05-22'),
('Simone', 'Costa', '1987-02-19', '039445566', '3331112200', 's.costa@mail.it', 'Via Volta 7, Monza', 'LIB-0011', '2023-06-01');
 
-- VIDEO (titoli di catalogo)
INSERT INTO video (titolo, nome_regista, cognome_regista, casa_produttrice, durata_min, genere) VALUES
('Il Viaggio', 'Marco', 'Bellini', 'Cinemax Studios', 118, 'Avventura'),
('Notte a Roma', 'Elena', 'Salviati', 'ItalCinema', 102, 'Drammatico'),
('Ridere Ancora', 'Paolo', 'Greco', 'ComicaFilm', 95, 'Commedia'),
('Ombre nel Buio', 'Silvia', 'Marchetti', 'DarkVision', 110, 'Horror'),
('Corsa Infinita', 'Giorgio', 'Testa', 'SpeedProd', 125, 'Azione'),
('Stelle Lontane', 'Anna', 'Cattaneo', 'GalaxyPictures', 130, 'Fantascienza');
 
-- ATTORE
INSERT INTO attore (nome, cognome) VALUES
('Marco', 'Ferri'),
('Laura', 'Santini'),
('Giulio', 'Pellegrini'),
('Beatrice', 'Longo'),
('Tommaso', 'Farina'),
('Camilla', 'De Luca'),
('Nicola', 'Serra'),
('Ilaria', 'Costantini');
 
-- VIDEO_ATTORE (cast per titolo)
INSERT INTO video_attore (video_id, attore_id) VALUES
(1, 1), (1, 2),
(2, 2), (2, 3),
(3, 4), (3, 5),
(4, 6), (4, 1),
(5, 7), (5, 8),
(6, 3), (6, 6);
 
-- COPIA_VIDEO (copie fisiche)
-- Alcune caricate da più di 90 giorni per testare la query di scadenza fornitore
INSERT INTO copia_video (video_id, fornitore_id, store_id, data_carico_fornitore, data_ritiro_fornitore) VALUES
(1, 1, 1, CURRENT_DATE - INTERVAL '120 days', (CURRENT_DATE - INTERVAL '120 days') + INTERVAL '90 days'),
(1, 1, 1, CURRENT_DATE - INTERVAL '30 days',  NULL),
(2, 2, 1, CURRENT_DATE - INTERVAL '95 days',  (CURRENT_DATE - INTERVAL '95 days') + INTERVAL '90 days'),
(3, 3, 2, CURRENT_DATE - INTERVAL '10 days',  NULL),
(4, 3, 3, CURRENT_DATE - INTERVAL '200 days', (CURRENT_DATE - INTERVAL '200 days') + INTERVAL '90 days'),
(5, 4, 4, CURRENT_DATE - INTERVAL '15 days',  NULL),
(6, 5, 5, CURRENT_DATE - INTERVAL '91 days',  (CURRENT_DATE - INTERVAL '91 days') + INTERVAL '90 days'),
(2, 6, 6, CURRENT_DATE - INTERVAL '5 days',   NULL),
(3, 6, 7, CURRENT_DATE - INTERVAL '60 days',  NULL),
(1, 1, 8, CURRENT_DATE - INTERVAL '100 days', (CURRENT_DATE - INTERVAL '100 days') + INTERVAL '90 days'),
(2, 2, 2, CURRENT_DATE - INTERVAL '45 days',  NULL),
(5, 4, 4, CURRENT_DATE - INTERVAL '20 days',  NULL),
(6, 5, 5, CURRENT_DATE - INTERVAL '70 days',  NULL),
(3, 3, 3, CURRENT_DATE - INTERVAL '8 days',   NULL),
(4, 3, 6, CURRENT_DATE - INTERVAL '110 days', (CURRENT_DATE - INTERVAL '110 days') + INTERVAL '90 days'),
(1, 1, 7, CURRENT_DATE - INTERVAL '25 days',  NULL);
 
-- TARIFFA (fasce, minimo 5 giorni di noleggio)
INSERT INTO tariffa (prezzo_giorno, gg_min, gg_max) VALUES
(3.00, 5, 10),
(2.50, 11, 20),
(2.00, 21, 30),
(1.50, 31, 39),
(1.00, 40, 50);
 
-- SCONTO (valori ENUM)
INSERT INTO sconto (descrizione, percentuale_sconto) VALUES
('5 noleggi', 0.20),
('10 noleggi', 0.60),
('25 noleggi', 0.15),
('50 noleggi', 0.25);
 
-- NOLEGGIO
-- Casi particolari sui campi nullable (sconto_id, data_restituzione, stato_restituzione)
INSERT INTO noleggio (copia_id, cliente_id, staff_id, tariffa_id, sconto_id, start_date, end_date, data_restituzione, stato_restituzione, stato_noleggio, importo_pagato) VALUES
(2, 1, 2, 1, NULL, CURRENT_DATE - INTERVAL '3 days',  CURRENT_DATE + INTERVAL '2 days',  NULL,                             NULL,          'Attivo', 15.00),
(4, 2, 5, 2, 2,    CURRENT_DATE - INTERVAL '15 days', CURRENT_DATE - INTERVAL '3 days',  CURRENT_DATE - INTERVAL '3 days', 'Buono',       'Chiuso', 12.00),
(6, 3, 9, 1, NULL, CURRENT_DATE - INTERVAL '1 days',  CURRENT_DATE + INTERVAL '5 days',  NULL,                             NULL,          'Attivo', 18.00),
(8, 4, 6, 4, 3,    CURRENT_DATE - INTERVAL '35 days', CURRENT_DATE - INTERVAL '3 days',  CURRENT_DATE - INTERVAL '3 days', 'Danneggiato', 'Chiuso', 40.80),
(9, 5, 7, 1, NULL, CURRENT_DATE - INTERVAL '9 days',  CURRENT_DATE,                      CURRENT_DATE,                     'Buono',       'Chiuso', 27.00),
(10, 6, 12, 1, 1,  CURRENT_DATE - INTERVAL '7 days',  CURRENT_DATE - INTERVAL '2 days',  CURRENT_DATE - INTERVAL '2 days', 'Buono',       'Chiuso', 12.00);

-- Modifiche per copie inserite in precedenza, per rendere coerenti i nuovi noleggi
UPDATE copia_video
SET data_ritiro_fornitore = NULL
WHERE copia_id IN (1,3,5);

UPDATE copia_video
SET data_ritiro_fornitore = CURRENT_DATE - INTERVAL '1 day'
WHERE copia_id = 10;

UPDATE copia_video
SET data_ritiro_fornitore = CURRENT_DATE - INTERVAL '10 days'
WHERE copia_id = 15;

-- Nuovi inserimenti (14 record aggiuntivi)
INSERT INTO noleggio (copia_id, cliente_id, staff_id, tariffa_id, sconto_id, start_date, end_date, data_restituzione, stato_restituzione, stato_noleggio, importo_pagato) VALUES
(1, 1, 1, 1, NULL, CURRENT_DATE - INTERVAL '120 days', CURRENT_DATE - INTERVAL '115 days', CURRENT_DATE - INTERVAL '115 days', 'Buono', 'Chiuso', 15.00),
(1, 1, 1, 1, NULL, CURRENT_DATE - INTERVAL '100 days', CURRENT_DATE - INTERVAL '95 days', CURRENT_DATE - INTERVAL '95 days', 'Buono', 'Chiuso', 15.00),
(2, 2, 1, 1, NULL, CURRENT_DATE - INTERVAL '95 days', CURRENT_DATE - INTERVAL '90 days', CURRENT_DATE - INTERVAL '90 days', 'Buono', 'Chiuso', 15.00),
(3, 6, 7, 1, NULL, CURRENT_DATE - INTERVAL '60 days', CURRENT_DATE - INTERVAL '55 days', CURRENT_DATE - INTERVAL '55 days', 'Buono', 'Chiuso', 15.00),
(4, 3, 3, 2, NULL, CURRENT_DATE - INTERVAL '200 days', CURRENT_DATE - INTERVAL '189 days', CURRENT_DATE - INTERVAL '189 days', 'Buono', 'Chiuso', 27.50),
(5, 4, 4, 1, NULL, CURRENT_DATE - INTERVAL '20 days', CURRENT_DATE - INTERVAL '15 days', CURRENT_DATE - INTERVAL '15 days', 'Buono', 'Chiuso', 15.00),
(6, 5, 5, 3, NULL, CURRENT_DATE - INTERVAL '91 days', CURRENT_DATE - INTERVAL '70 days', CURRENT_DATE - INTERVAL '70 days', 'Buono', 'Chiuso', 42.00),
(8, 6, 7, 1, NULL, CURRENT_DATE - INTERVAL '30 days', CURRENT_DATE - INTERVAL '25 days', CURRENT_DATE - INTERVAL '25 days', 'Buono', 'Chiuso', 15.00),
(10, 1, 8, 1, NULL, CURRENT_DATE - INTERVAL '100 days', CURRENT_DATE - INTERVAL '95 days', CURRENT_DATE - INTERVAL '95 days', 'Buono', 'Chiuso', 15.00),
(12, 4, 4, 1, NULL, CURRENT_DATE - INTERVAL '20 days', CURRENT_DATE - INTERVAL '15 days', CURRENT_DATE - INTERVAL '15 days', 'Buono', 'Chiuso', 15.00),
(13, 5, 5, 3, NULL, CURRENT_DATE - INTERVAL '70 days', CURRENT_DATE - INTERVAL '49 days', CURRENT_DATE - INTERVAL '49 days', 'Buono', 'Chiuso', 42.00),
(14, 3, 3, 1, NULL, CURRENT_DATE - INTERVAL '8 days', CURRENT_DATE - INTERVAL '3 days', CURRENT_DATE - INTERVAL '3 days', 'Buono', 'Chiuso', 15.00),
(15, 3, 6, 2, NULL, CURRENT_DATE - INTERVAL '110 days', CURRENT_DATE - INTERVAL '99 days', CURRENT_DATE - INTERVAL '99 days', 'Buono', 'Chiuso', 27.50),
(16, 1, 7, 1, NULL, CURRENT_DATE + INTERVAL '5 days', CURRENT_DATE + INTERVAL '10 days', NULL, NULL, 'Prenotato', 15.00);


-- INCENTIVO (log storico, richiede staff_id già esistenti)
INSERT INTO incentivo (staff_id, periodo, soglia_raggiunta, importo) VALUES
(2, '2026-06-01', 20, 50.00),
(5, '2026-06-01', 40, 100.00),
(9, '2026-06-01', 60, 200.00);



--- Queries ---

-- Stato del catalogo e calcolo disponibilità copie in tempo reale per genere e titolo
SELECT 
    video.titolo,
    video.genere,
    store.localita AS "Negozio",
    COUNT(copia_video.copia_id) AS "Copie Totali Assegnate",
    COUNT(copia_video.copia_id) FILTER (
        WHERE copia_video.data_ritiro_fornitore IS NULL 
        AND copia_video.copia_id NOT IN (
            SELECT noleggio.copia_id 
            FROM noleggio 
            WHERE noleggio.stato_noleggio = 'Attivo'
        )
    ) AS "Copie Disponibili Ora"
FROM video
JOIN copia_video ON video.video_id = copia_video.video_id
JOIN store ON copia_video.store_id = store.store_id
-- WHERE video.genere = 'Fantascienza' -- per ricerca sul catalogo per genere
-- WHERE video.titolo ILIKE '%Matrix%' -- per ricerca sul catalogo per titolo
GROUP BY video.titolo, video.genere, store.localita
ORDER BY video.titolo, store.localita;


-- Calcolo dell'incasso giornaliero per singolo punto vendita e per addetto
SELECT 
    store.localita AS "Negozio",
    staff.nome AS "Nome Addetto",
    staff.cognome AS "Cognome Addetto",
    SUM(noleggio.importo_pagato) AS incasso_totale_giornaliero
FROM noleggio
JOIN staff ON noleggio.staff_id = staff.staff_id
JOIN store ON staff.store_id = store.store_id
WHERE noleggio.start_date = CURRENT_DATE -- Calcolato sul giorno corrente ma modificabile
GROUP BY store.localita, staff.staff_id, staff.nome, staff.cognome
ORDER BY store.localita, incasso_totale_giornaliero DESC;


-- Calcolo del volume mensile dei noleggi per addetto per la verifica del raggiungimento soglie incentivi
SELECT 
    staff.staff_id,
    staff.nome,
    staff.cognome,
    store.localita AS "Negozio",
    COUNT(noleggio.noleggio_id) AS numero_noleggi_mese_corrente
FROM staff
JOIN store ON staff.store_id = store.store_id
LEFT JOIN noleggio
    ON staff.staff_id = noleggio.staff_id
   AND EXTRACT(MONTH FROM noleggio.start_date) = EXTRACT(MONTH FROM CURRENT_DATE)
   AND EXTRACT(YEAR FROM noleggio.start_date) = EXTRACT(YEAR FROM CURRENT_DATE)
GROUP BY staff.staff_id, staff.nome, staff.cognome, store.localita
ORDER BY numero_noleggi_mese_corrente DESC;


-- Storico noleggi per un cliente specifico
SELECT 
    noleggio.noleggio_id,
    video.titolo,
    noleggio.start_date,
    noleggio.end_date,
    noleggio.data_restituzione,
    noleggio.stato_noleggio,
    noleggio.importo_pagato
FROM noleggio
JOIN copia_video ON noleggio.copia_id = copia_video.copia_id
JOIN video ON copia_video.video_id = video.video_id
-- WHERE noleggio.cliente_id = 1 -- sostituisci con ID del cliente da visualizzare
ORDER BY noleggio.start_date DESC; -- in ordine decrescente


-- Calcolo scadenza ritiro fornitore
SELECT
    copia_video.copia_id,
    video.titolo,
    fornitore.nome AS Fornitore,
    store.localita AS Negozio,
    copia_video.data_carico_fornitore,
    CAST(copia_video.data_carico_fornitore + INTERVAL '90 days' AS DATE) AS data_scadenza_fornitore, -- creo colonna calcolandola, perché non esiste già in db, e CAST per togliere orario
    (copia_video.data_carico_fornitore + INTERVAL '90 days') <= CURRENT_DATE AS "Scaduta"
FROM copia_video
JOIN video ON video.video_id = copia_video.video_id
JOIN fornitore ON fornitore.fornitore_id = copia_video.fornitore_id
JOIN store ON store.store_id = copia_video.store_id
-- WHERE copia_video.data_ritiro_fornitore IS NULL -- mostra solo quelle non scadute
ORDER BY data_scadenza_fornitore;


-- EXTRA: elenco prenotazioni (titoli prenotati dai clienti per un ritiro futuro)
SELECT 
    noleggio.noleggio_id,
    cliente.nome AS nome_cliente,
    cliente.cognome AS cognome_cliente,
    cliente.telefono,
    video.titolo,
    store.localita AS negozio_ritiro,
    noleggio.start_date AS data_ritiro_prevista,
    noleggio.end_date AS data_restituzione_prevista
FROM noleggio
JOIN cliente ON noleggio.cliente_id = cliente.cliente_id
JOIN copia_video ON noleggio.copia_id = copia_video.copia_id
JOIN video ON copia_video.video_id = video.video_id
JOIN store ON copia_video.store_id = store.store_id
WHERE noleggio.stato_noleggio = 'Prenotato'
ORDER BY noleggio.start_date ASC; -- ordinato dal ritiro più imminente a quello più lontano


-- EXTRA: report dei video restituiti danneggiati con calcolo importo rimborsi da emettere verso il fornitore
SELECT 
    noleggio.noleggio_id,
    video.titolo,
    fornitore.nome AS "Fornitore",
    cliente.cognome AS "Cognome Cliente",
    noleggio.data_restituzione,
    noleggio.importo_pagato AS "Quota Noleggio",
    -- Esempio di calcolo penale: 3 volte il prezzo base della tariffa giornaliera associata
    (tariffa.prezzo_giorno * 3) AS "Addebito Danno Cliente"
FROM noleggio
JOIN copia_video ON noleggio.copia_id = copia_video.copia_id
JOIN video ON copia_video.video_id = video.video_id
JOIN fornitore ON copia_video.fornitore_id = fornitore.fornitore_id
JOIN cliente ON noleggio.cliente_id = cliente.cliente_id
JOIN tariffa ON noleggio.tariffa_id = tariffa.tariffa_id
WHERE noleggio.stato_restituzione = 'Danneggiato'
ORDER BY noleggio.data_restituzione DESC;